import 'package:flutter/material.dart';

class DisclaimerScreen extends StatelessWidget {
  const DisclaimerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final w = MediaQuery.of(context).size.width;
    final bool isDesktop = w > 600;

    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color(0xFF90CAF9),
        elevation: 0,
        centerTitle: true,
        title: const Text(
          "Disclaimer",
          style: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
      ),
      body: Container(
        width: double.infinity,
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFFB39DDB), Color(0xFF90CAF9)],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: Center(
          child: SizedBox(
            width: isDesktop ? 700 : double.infinity,
            child: ListView(
              padding: const EdgeInsets.all(20),
              children: const [
                _DisclaimerCard(
                  icon: Icons.auto_awesome,
                  title: "AI-Generated Responses",
                  content:
                  "All responses provided by SmileAI are generated by artificial intelligence. "
                      "The content is created automatically and may not always be accurate, complete, "
                      "or up-to-date.",
                ),
                _DisclaimerCard(
                  icon: Icons.medical_information_outlined,
                  title: "Not Professional Advice",
                  content:
                  "SmileAI is not a medical, psychological, legal, or professional service. "
                      "Any advice or suggestions given should not be considered a substitute for "
                      "professional consultation.",
                ),
                _DisclaimerCard(
                  icon: Icons.psychology_alt_outlined,
                  title: "Mental Health Notice",
                  content:
                  "While SmileAI aims to provide emotional comfort and stress relief, "
                      "it should not be used as a replacement for therapy or mental health treatment. "
                      "If you are experiencing severe distress, please seek help from a qualified professional.",
                ),
                _DisclaimerCard(
                  icon: Icons.warning_amber_rounded,
                  title: "User Responsibility",
                  content:
                  "By using SmileAI, you acknowledge that you are responsible for how you interpret "
                      "and act upon the information provided by the AI.",
                ),
                _DisclaimerCard(
                  icon: Icons.verified_user_outlined,
                  title: "Acceptance of Terms",
                  content:
                  "By continuing to use this application, you agree to this disclaimer and understand "
                      "the limitations of AI-generated content.",
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _DisclaimerCard extends StatelessWidget {
  final IconData icon;
  final String title;
  final String content;

  const _DisclaimerCard({
    required this.icon,
    required this.title,
    required this.content,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 6,
      margin: const EdgeInsets.only(bottom: 20),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      child: Padding(
        padding: const EdgeInsets.all(18),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 28, color: Color(0xFF7E57C2)),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    title,
                    style: const TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(
              content,
              style: const TextStyle(
                fontSize: 15,
                height: 1.5,
                color: Colors.black87,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
