import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final w = MediaQuery.of(context).size.width;
    final bool isDesktop = w > 600;

    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color(0xFF90CAF9),
        elevation: 0,
        centerTitle: true,
        title: const Text(
          "Privacy Policy",
          style: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
      ),
      body: Container(
        width: double.infinity,
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFFB39DDB), Color(0xFF90CAF9)],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: Center(
          child: SizedBox(
            width: isDesktop ? 750 : double.infinity,
            child: ListView(
              padding: const EdgeInsets.all(20),
              children: const [
                _PolicyCard(
                  icon: Icons.policy_outlined,
                  title: "Introduction",
                  content:
                  "SmileAI respects your privacy and is committed to protecting your personal data. "
                      "This Privacy Policy explains how information is collected, used, and safeguarded "
                      "when you use our application.",
                ),
                _PolicyCard(
                  icon: Icons.person_outline,
                  title: "Information We Collect",
                  content:
                  "We may collect basic account information such as email address for authentication purposes. "
                      "Chat messages are stored only to improve user experience, session continuity, and app functionality.",
                ),
                _PolicyCard(
                  icon: Icons.chat_bubble_outline,
                  title: "Chat Data & AI Responses",
                  content:
                  "All chat responses are generated by artificial intelligence. "
                      "Conversations may be processed by AI systems to generate replies, "
                      "but they are not used to personally identify users.",
                ),
                _PolicyCard(
                  icon: Icons.lock_outline,
                  title: "Data Security",
                  content:
                  "We use reasonable security measures to protect your information. "
                      "However, no digital system is completely secure, and absolute security cannot be guaranteed.",
                ),
                _PolicyCard(
                  icon: Icons.share_outlined,
                  title: "Data Sharing",
                  content:
                  "SmileAI does not sell, trade, or rent your personal information to third parties. "
                      "Data may only be shared when required by law or to maintain app functionality.",
                ),
                _PolicyCard(
                  icon: Icons.settings_backup_restore,
                  title: "Your Rights",
                  content:
                  "You have the right to access, update, or delete your account information. "
                      "You may stop using the app at any time if you do not agree with this policy.",
                ),
                _PolicyCard(
                  icon: Icons.update_outlined,
                  title: "Policy Updates",
                  content:
                  "This Privacy Policy may be updated from time to time. "
                      "Continued use of SmileAI indicates acceptance of any changes made.",
                ),
                _PolicyCard(
                  icon: Icons.contact_mail_outlined,
                  title: "Contact Us",
                  content:
                  "If you have any questions or concerns regarding this Privacy Policy, "
                      "please contact us at:\n\nsupport@smileai.app",
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _PolicyCard extends StatelessWidget {
  final IconData icon;
  final String title;
  final String content;

  const _PolicyCard({
    required this.icon,
    required this.title,
    required this.content,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 6,
      margin: const EdgeInsets.only(bottom: 20),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      child: Padding(
        padding: const EdgeInsets.all(18),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 28, color: Color(0xFF7E57C2)),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    title,
                    style: const TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(
              content,
              style: const TextStyle(
                fontSize: 15,
                height: 1.5,
                color: Colors.black87,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
